import HeroSection from './sections/HeroSection'
import type { SectionDefinition } from './types/portfolio'

export const sectionDefinitions: SectionDefinition[] = [
  {
    id: 'hero',
    label: 'Hero',
    preloadOffset: '0px 0px',
    placeholderClassName: 'min-h-[100svh]',
    themeTone: 'hero',
    navVisible: true,
    eager: true,
    component: HeroSection,
  },
  {
    id: 'summary',
    label: 'Summary',
    preloadOffset: '20% 0px',
    placeholderClassName: 'min-h-[44rem]',
    themeTone: 'surface',
    navVisible: false,
    loader: () => import('./sections/AboutSection'),
  },
  {
    id: 'experience',
    label: 'Experience',
    preloadOffset: '25% 0px',
    placeholderClassName: 'min-h-[56rem]',
    themeTone: 'surface-alt',
    navVisible: true,
    loader: () => import('./sections/ExperienceSection'),
  },
  {
    id: 'skills',
    label: 'Skills',
    preloadOffset: '30% 0px',
    placeholderClassName: 'min-h-[42rem]',
    themeTone: 'surface',
    navVisible: false,
    loader: () => import('./sections/SkillsSection'),
  },
  {
    id: 'core-technologies',
    label: 'Core Technologies',
    preloadOffset: '30% 0px',
    placeholderClassName: 'min-h-[34rem]',
    themeTone: 'surface-alt',
    navVisible: false,
    loader: () => import('./sections/CoreTechnologiesSection'),
  },
  {
    id: 'code-showcase',
    label: 'Code Blocks',
    preloadOffset: '30% 0px',
    placeholderClassName: 'min-h-[34rem]',
    themeTone: 'surface',
    navVisible: false,
    loader: () => import('./sections/CodeShowcaseSection'),
  },
  {
    id: 'knowledge',
    label: 'Knowledge',
    preloadOffset: '30% 0px',
    placeholderClassName: 'min-h-[52rem]',
    themeTone: 'surface',
    navVisible: false,
    loader: () => import('./sections/KnowledgeSection'),
  },
  {
    id: 'projects',
    label: 'Projects',
    preloadOffset: '35% 0px',
    placeholderClassName: 'min-h-[50rem]',
    themeTone: 'surface-alt',
    navVisible: false,
    loader: () => import('./sections/ProjectsSection'),
  },
  {
    id: 'education',
    label: 'Education',
    preloadOffset: '30% 0px',
    placeholderClassName: 'min-h-[40rem]',
    themeTone: 'surface',
    navVisible: false,
    loader: () => import('./sections/EducationSection'),
  },
  {
    id: 'contact',
    label: 'Contact',
    preloadOffset: '40% 0px',
    placeholderClassName: 'min-h-[34rem]',
    themeTone: 'surface-alt',
    navVisible: true,
    loader: () => import('./sections/ContactSection'),
  },
]
